version: "3.9"

services:
  traefik:
    image: traefik:v2.11
    command:
      - "--api.insecure=false"                    # Dashboard sécurisé
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
    networks:
      - backend
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any

  postgres:
    image: postgres:16.8
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-volume:/var/lib/postgresql/data
      - ./docker/config/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  postgres-backup:
    image: prodrigestivill/postgres-backup-local
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
    volumes:
      - ./backups:/backups
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: ${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HOSTNAME: auth.samagp.com
      KC_PROXY: edge
    command: start --optimized --import-realm
    volumes:
      - keycloak-data:/opt/keycloak/data
      - ./docker/config/keycloak:/opt/keycloak/data/import
      - ./themes/event:/opt/keycloak/providers/
      - ./themes/theme/samagp:/opt/keycloak/themes/samagp
    networks:
      - backend
    depends_on:
      - postgres
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`auth.samagp.com`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls.certresolver=myresolver"

  api:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_APPLICATION_NAME: ${SPRING_APPLICATION_NAME}
      REALM: ${REALM}
      AUTH_SERVER_URL: https://auth.samagp.com
    networks:
      - backend
    depends_on:
      - postgres
      - keycloak
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=Host(`api.samagp.com`)"
        - "traefik.http.routers.api.entrypoints=websecure"
        - "traefik.http.routers.api.tls.certresolver=myresolver"

  samagp-angular:
    build:
      context: ../test/samagp-angular
      dockerfile: Dockerfile
    environment:
      - API_BASE_URL=https://api.samagp.com
      - KEYCLOAK_URL=https://auth.samagp.com
    networks:
      - backend
    depends_on:
      - api
      - keycloak
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.angular.rule=Host(`samagp.com`)"
        - "traefik.http.routers.angular.entrypoints=websecure"
        - "traefik.http.routers.angular.tls.certresolver=myresolver"

volumes:
  db-volume:
  keycloak-data:
  letsencrypt:

networks:
  backend:
    driver: overlay
