version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    container_name: keycloak
    ports:
      - 8090:8080
    networks:
      - db-network
    command: start-dev --import-realm
    depends_on:
      - postgres

  postgres:
    image: postgres:16.8
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - db-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: samagp

  api:
    image: samagp-api:latest
    container_name: samagp-api
    ports:
      - "8082:8082"
    networks:
      - db-network
    depends_on:
      - keycloak
      - postgres

  samagp-angular:
    image: samagp-angular:latest
    container_name: samagp-angular
    ports:
      - "4200:80"
    networks:
      - db-network
    depends_on:
      - api
      - keycloak

networks:
  db-network:
    driver: bridge
