services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    container_name: keycloak
    environment:
      # Keycloak settings
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: ${KC_DB}
      KC_DB_URL_HOST: ${KC_DB_URL_HOST}
      KC_DB_URL_DATABASE: ${KC_DB_URL_DATABASE}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
    #      KC_HOSTNAME: localhost

    ports:
      - 8090:8080
    depends_on:
      - postgres
    volumes:
      - keycloak-data:/opt/keycloak/data
      - ./docker/config/keycloak:/opt/keycloak/data/import
    command: start-dev --import-realm
    networks:
      - db-network
    restart: on-failure

  postgres:
    container_name: postgres
    image: postgres:16.8
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
    volumes:
      - db-volume:/data/postgres
      - ./docker/config/init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./logs:/var/log/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 30s
      retries: 3
    networks:
      - db-network
    restart: unless-stopped

  # Flyway
  flyway:
    image: flyway/flyway:9.22
    container_name: flyway
    command: -connectRetries=60 migrate
    volumes:
      - ./src/resources/migration/structure:/flyway/sql/structure
      - ./src/resources/migration/data:/flyway/sql/data
    environment:
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - FLYWAY_USER=${POSTGRES_USER}
      - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
      - FLYWAY_BASELINE_ON_MIGRATE=true
      - FLYWAY_SCHEMAS=public
    depends_on:
      - postgres
    networks:
      - db-network


  api:
    container_name: samagp-api
    build: .
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      LOG_PATH: ${LOG_PATH}
      SPRING_APPLICATION_NAME: ${SPRING_APPLICATION_NAME}
      REALM: ${REALM}
      AUTH_SERVER_URL: ${AUTH_SERVER_URL}
      KEYCLOAK_USERNAME: ${KEYCLOAK_USERNAME}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      GRANT_TYPE: ${GRANT_TYPE}
      KEYCLOAK_HOST: ${KEYCLOAK_HOST}
      KEYCLOAK_PORT: ${KEYCLOAK_PORT}
      KEYCLOAK_INTERNAL_URL: ${KEYCLOAK_INTERNAL_URL}
      KEYCLOAK_EXTERNAL_URL: ${KEYCLOAK_EXTERNAL_URL}
    ports:
      - "8082:8082"
    volumes:
      - ./logs:/var/log/myapp
    networks:
      - db-network
    depends_on:
      - postgres
      - keycloak
    restart: always

networks:
  db-network:
    driver: bridge

volumes:
  db-volume:
  keycloak-data:
