services:
  postgres:
    container_name: postgres
    image: postgres:14.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: samagp
      PGDATA: /data/postgres
    volumes:
      - db-volume:/data/postgres
      - ./init:/docker-entrypoint-initdb.d
      - ./logs:/var/log/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 30s
      retries: 3
    networks:
      - db-network
    restart: unless-stopped


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - db-network
    restart: unless-stopped

#  api:
#    container_name: samagp-api
#    #image: ousmanevincent/gestion-stock
#    build: .
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/samagp
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#      LOG_PATH: /var/log/myapp
#      SPRING_APPLICATION_NAME: samagp-api
#    ports:
#      - "8082:8082"
#    volumes:
#      - ./logs:/var/log/myapp
#    networks:
#      - db-network
#    depends_on:
#      - postgres
#    #      - loki
#    #      - tempo
#    restart: always


networks:
  db-network:
    driver: bridge

volumes:
  db-volume:


