services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: samagp
      POSTGRES_PASSWORD: samagp
      POSTGRES_DB: samagp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - samagp-network

  samagp-api-ms:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/samagp
      SPRING_DATASOURCE_USERNAME: samagp
      SPRING_DATASOURCE_PASSWORD: samagp
      APP_ENV: dev
    networks:
      - samagp-network

volumes:
  postgres_data:

networks:
  samagp-network:
    driver: bridge

