apiVersion: apps/v1
kind: Deployment
metadata:
  name: sama-gp-annonce-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sama-gp-annonce-image
  template:
    metadata:
      labels:
        app: sama-gp-annonce-image
    spec:
      containers:
        - name: sama-gp-annonce-image
          image: souleygassama/sama-gp-annonce-image:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
