#Database
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: postgres
POSTGRES_SQL_HOST: localhost
#POSTGRES_SQL_HOST: postgres  docker
POSTGRES_SQL_PORT: 5435
POSTGRES_SQL_DB: samagp

#Server
ACTIVE_PROFILE: dev

#Keycloack
REALM: samagp
AUTH-SERVER-URL: http://127.0.0.1
KEYCLOAK_PORT: 8090
KEYCLOAK_USERNAME: samagp
KEYCLOAK_PASSWORD: samagp
GRANT_TYPE: password
