cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

# Configuration upload fichiers
file:
    upload-dir: ./uploads
#    max-file-size: 10MB
#    max-request-size: 10MB


spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}



  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  web:
    resources:
      static-locations: "classpath:/static/,file:${file.upload-dir}"

  stripe:
    secret-key: ${STRIPE_SECRET_KEY:sk_test_51KAh93GLF9nttjSE3StevPyrDluu5O78IKnwe0L0aRXkpQJoy8RfhRnQANodjzlUykjGmFL0Zog8VSXsmjxEKvFh007EcBDDCY}
    public-key: ${STRIPE_PUBLIC_KEY:pk_test_51KAh93GLF9nttjSEBVXlxgnb1IVhmvgbffjn7cfVlXrFXbT9mCxCnQhBdOhE8YAACq9ws8zRzP3xzphAbQy2w2if00BZTrxYBv}
    webhook-secret: ${STRIPE_WEBHOOK_SECRET:whsec_...}

  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: "${KEYCLOAK_EXTERNAL_URL:http://localhost:8090}/realms/samagp"


#         issuer-uri: "${KEYCLOAK_INTERNAL_URL:http://keycloak:8080}/realms/samagp"

#        opaque-token:
#          introspection-uri: http://localhost:8090/realms/samagp/protocol/openid-connect/token/introspect
#          client-id: samagp-api
#          client-secret: samagp-secret

  application:
    name: samagp

  datasource:
    url: jdbc:postgresql://${POSTGRES_SQL_HOST}:${POSTGRES_SQL_PORT}/${POSTGRES_SQL_DB}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Paris
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  sql:
    init:
      mode: always
      data-locations: classpath:/data/data.sql

server:
  port: 8082
  servlet:
    context-path: /samagp

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html
    oauth2:
      client-id: samagp-api
      client-secret: samagp-secret
      use-pkce-with-authorization-code-grant: true
      scopes: openid,profile
    oauth:
      authorization-url: "${KEYCLOAK_EXTERNAL_URL:http://localhost:8090}/realms/samagp/protocol/openid-connect/auth"
      token-url: "${KEYCLOAK_INTERNAL_URL:http://localhost:8090}/realms/samagp/protocol/openid-connect/token"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

keycloak:
  realm: ${REALM}
  auth-server-url: ${AUTH_SERVER_URL:http://localhost:8090/auth}
  resource: admin-cli
  client-id: ${KEYCLOAK_CLIENT_ID:admin-cli}
  client-secret: samagp-secret
  credentials:
    grant-type: ${GRANT_TYPE}
    username: ${KEYCLOAK_USERNAME}
    password: ${KEYCLOAK_PASSWORD}
  admin:
    username: samagp
    password: samagp


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    sn.fr.samagp.configuration.security: DEBUG
