version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
    ports:
      - 8090:8080
    depends_on:
      - postgres
    volumes:
      - keycloak-data:/opt/keycloak/data
      - ./config/keycloak:/opt/keycloak/data/import
    command: start-dev --import-realm
    networks:
      - db-network
    restart: on-failure

networks:
  db-network:
    name: db-network

volumes:
  keycloak-data:
