apiVersion: apps/v1
kind: Deployment
metadata:
  name: samagp-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: samagp-api
  template:
    metadata:
      labels:
        app: samagp-api
    spec:
      containers:
        - name: samagp-api
          image: samagp/samagp-api:latest
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: samagp-api-config
            - secretRef:
                name: postgres-secret
