apiVersion: v1
kind: Service
metadata:
  name: samagp-api-service
spec:
  selector:
    app: samagp-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
      nodePort: 30080
  type: NodePort
